import Image from "next/image";
import styles from "./connect.module.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Fsx Connect",
  description: "Generated by create next app",
};

export default function FsxConnect() {
  return (
    <div
      className={`${roboto.variable} ${styles.fsxSection} ${styles.fsxConnectPage}`}
    >
      <section className={styles.fsxConnectContainer}>
        <section className={styles.heroSection}>
          <div className={styles.heroTextContainer}>
            <h2 className={styles.heroTitle}>FSX Connect</h2>
            <p className={styles.heroDescription}>
              Building meaningful networks for growth and collaboration. Connect
              with entrepreneurs, investors, mentors, and innovators across
              Africa and beyond.
            </p>
            <section className={styles.heroBtnContainer}>
              <button className={styles.exploreBtn}>Explore Network</button>
              <button className={styles.joinBtn}>Join Community</button>
            </section>
          </div>
          <div className={styles.heroImageContainer}>
            <Image
              src="/fsx_connect_hero_img.svg"
              alt="FSX Connect"
              width={500}
              height={500}
              //layout="fill" //When you use layout="fill" (Next.js <Image>), the image is set to absolutely position itself and fill its parent container. You do not set width or height on the <Image> itself. But you must give the parent container a size (width + height), otherwise the image has nothing to "fill".
              className={styles.heroImage}
              objectFit="cover"
            />
          </div>
        </section>

        <section className={styles.cardParticipation}>
          <div className={styles.communityMem}>
            <h3 className={styles.communityMemCount}>5000+</h3>
            <p className={styles.communityMemTitle}>Community Members</p>
          </div>
          <div className={styles.communityMem}>
            <h3 className={styles.successfulCount}>100+</h3>
            <p className={styles.successfulTitle}>Successful Partnerships</p>
          </div>
          <div className={styles.communityMem}>
            <h3 className={styles.industryExpertsCount}>200+</h3>
            <p className={styles.industryExpertsTitle}>Industry Experts</p>
          </div>
          <div className={styles.communityMem}>
            <h3 className={styles.countriesCount}>5+</h3>
            <p className={styles.countriesTitle}>Countries Represented</p>
          </div>
        </section>
        <section className={styles.connectionSection}>
          <h4 className={styles.connectionTitle}>Our Connection Services</h4>
          <p className={styles.connectionDescription}>
            We facilitate meaningful connections through specialized networks
            and programs designed to foster collaboration and growth.
          </p>
          <div className={styles.connectionCardsContainer}>
            <div className={styles.connectionCard}>
              <Image
                src="/networkIcon.svg"
                alt="Network Icon"
                width={60}
                height={60}
                className={styles.cardIcon}
              />
              <h5 className={styles.cardTitle}>Professional Networks</h5>
              <p className={styles.cardDescription}>
                Connect with like-minded professionals, entrepreneurs, and
                innovators in your industry and beyond through curated
                networking events and forums.
              </p>
            </div>
            <div className={styles.connectionCard}>
              <Image
                src="/investor-relations-icon.svg"
                alt="Investor Relations Icon"
                width={60}
                height={60}
                className={styles.cardIcon}
              />
              <h5 className={styles.cardTitle}>Investor Relations</h5>
              <p className={styles.cardDescription}>
                Bridge the gap between innovative startups and investors looking
                for the next breakthrough opportunity with our matchmaking
                platform.
              </p>
            </div>
            <div className={styles.connectionCard}>
              <Image
                src="/mentor-matching-icon.svg"
                alt="Mentor Matching Icon"
                width={60}
                height={60}
                className={styles.cardIcon}
              />
              <h5 className={styles.cardTitle}>Mentorship Matching</h5>
              <p className={styles.cardDescription}>
                Intelligent pairing of mentors and mentees based on goals,
                experience, and growth objectives to maximize learning and
                development.
              </p>
            </div>
            <div className={styles.connectionCard}>
              <Image
                src="/networkIcon.svg"
                alt="Startup Ecosystem Icon"
                width={60}
                height={60}
                className={styles.cardIcon}
              />
              <h5 className={styles.cardTitle}>Startup Ecosystem</h5>
              <p className={styles.cardDescription}>
                Access a vibrant ecosystem of startups, incubators, and
                accelerators to fuel innovation and entrepreneurial growth
                across Africa.
              </p>
            </div>
            <div className={styles.connectionCard}>
              <Image
                src="/partnership-oppurtunity-icon.svg"
                alt="Partnership Opportunity Icon"
                width={60}
                height={60}
                className={styles.cardIcon}
              />
              <h5 className={styles.cardTitle}>Partnership Opportunities</h5>
              <p className={styles.cardDescription}>
                Discover strategic partnership opportunities with corporations,
                governments, and NGOs to scale your impact and reach.
              </p>
            </div>
            <div className={styles.connectionCard}>
              <Image
                src="/networkIcon.svg"
                alt="Executive network Icon"
                width={60}
                height={60}
                className={styles.cardIcon}
              />
              <h5 className={styles.cardTitle}>Executive Network</h5>
              <p className={styles.cardDescription}>
                Connect with C-suite executives and senior leaders for
                high-level strategic discussions and collaboration
                opportunities.
              </p>
            </div>
          </div>
        </section>

        <section className={styles.joinCommunitySection}>
          <h4 className={styles.joinCommunityTitle}>Our Network Communities</h4>
          <p className={styles.joinCommunityDescription}>
            Join specialized communities tailored to different professional
            needs and interests.
          </p>
          <div className={styles.communityCardsContainer}>
            <div className={styles.communityCard}>
              <div className={styles.communityCardImage}>
                <Image
                  src="/tech-innovator-icon.svg"
                  alt="tech innovator Icon"
                  width={400}
                  height={280}
                  objectFit="cover"
                  className={styles.communityImg}
                />
              </div>
              <div className={styles.communityCardContent}>
                <h5 className={styles.communityCardTitle}>
                  Tech Innovators Circle
                </h5>
                <p className={styles.communityCardDescription}>
                  A circle where tech enthusiast, founders, co-founders share
                  insights, challenges, opportunities and mentorships.
                </p>
              </div>
            </div>
            <div className={styles.communityCard}>
              <div className={styles.communityCardContent}>
                <h5 className={styles.communityCardTitle}>
                  Entrepreneurs Network
                </h5>
                <p className={styles.communityCardDescription}>
                  A network where fellow entrepreneurs and investors extends
                  insights, resources, partnerships and opportunities to
                  traction and growth stage businesses.
                </p>
              </div>
              <div className={styles.communityCardImage}>
                <Image
                  src="/enterpreneur-icon.svg"
                  alt="entrepreneur Icon"
                  width={400}
                  height={280}
                  objectFit="cover"
                  className={styles.communityImg}
                />
              </div>
            </div>
            <div className={styles.communityCard}>
              <div className={styles.communityCardImage}>
                <Image
                  src="/creative-mind-icon.svg"
                  alt="Creative Mind Icon"
                  width={400}
                  height={280}
                  objectFit="cover"
                  className={styles.communityImg}
                />
              </div>
              <div className={styles.communityCardContent}>
                <h5 className={styles.communityCardTitle}>
                  Creative Minds Alliance
                </h5>
                <p className={styles.communityCardDescription}>
                  An alliance where designers, artists, and creative
                  professionals collaborates.
                </p>
              </div>
            </div>
          </div>
          <button className={styles.joinCommunityButton}>Join community</button>
        </section>

        <section className={styles.whyJoinSection}>
          <h4 className={styles.whyJoinTitle}>Why Join FSX Connect?</h4>
          <p className={styles.whyJoinDescription}>
            Discover the unique advantages of being part of our growing
            community of professionals and innovators.
          </p>
          <div className={styles.whyJoinCardsContainer}>
            <div className={styles.whyJoinCard}>
              <Image
                width={60}
                height={60}
                src="/accelerated-growth-icon.svg"
                alt="Accelerated growth Icon"
              />
              <h5 className={styles.whyJoinCardTitle}>Accelerated Growth</h5>
              <p className={styles.whyJoinCardDescription}>
                Access resources, mentorship, and connections that propel your
                career or business forward.
              </p>
            </div>
            <div className={styles.whyJoinCard}>
              <Image
                width={60}
                height={60}
                src="/diverse-community-icon.svg"
                alt="Diverse Community Icon"
              />
              <h5 className={styles.whyJoinCardTitle}>Diverse Community</h5>
              <p className={styles.whyJoinCardDescription}>
                Connect with professionals from various industries, backgrounds,
                and expertise levels.
              </p>
            </div>

            <div className={styles.whyJoinCard}>
              <Image
                width={60}
                height={60}
                src="/innovation-hub-icon.svg"
                alt="Innovation Hub Icon"
              />
              <h5 className={styles.whyJoinCardTitle}>Innovation Hub</h5>
              <p className={styles.whyJoinCardDescription}>
                Be part of a dynamic ecosystem where new ideas are born and
                collaborations flourish.
              </p>
            </div>
          </div>
        </section>
        <section className={styles.ctaSection}>
          <div className={styles.ctaContainer}>
            <p className={styles.ctaDescription}>
              Are you passionate about giving back to the community to enhance
              nation building, youth development, SDG support and innovation
              strategy?
            </p>
            <button className={styles.ctaButton}>Join Us Today</button>
          </div>
          <Image
            // src="/ellipse-globe-icon.svg"
            src="/globes-icon.svg"
            alt="Call to Action Image"
            className={styles.ctaImage}
            width={550}
            height={350}
            objectFit="cover"
          />
        </section>
      </section>
    </div>
  );
}
